XetaIO/Xeta

src/Controller/BlogController.php

Fixed Like/Unlike errors

---

src/Template/Admin/Admin/home.ctp
src/Template/Admin/Articles/add.ctp
src/Template/Admin/Articles/edit.ctp
src/Template/Admin/Articles/index.ctp
src/Template/Admin/Attachments/add.ctp
src/Template/Admin/Attachments/edit.ctp
src/Template/Admin/Attachments/index.ctp
src/Template/Admin/Categories/add.ctp
src/Template/Admin/Categories/edit.ctp
src/Template/Admin/Categories/index.ctp
src/Template/Admin/Premium/Discounts/add.ctp
src/Template/Admin/Premium/Discounts/edit.ctp
src/Template/Admin/Premium/Discounts/index.ctp
src/Template/Admin/Premium/Offers/add.ctp
src/Template/Admin/Premium/Offers/edit.ctp
src/Template/Admin/Premium/Offers/index.ctp
src/Template/Admin/Premium/Premium/home.ctp
src/Template/Admin/Users/edit.ctp
src/Template/Admin/Users/index.ctp
src/Template/Admin/Users/search.ctp
src/Template/Element/Admin/header.ctp
src/Template/Element/Admin/interface.ctp
src/Template/Element/Admin/sidebar.ctp

Updated all admin strings to use a custom domain.

---

README.md

allow to install latest dev branch beacause as long as cakephp hit stable, the app is likely to break.
Also use --prefer-dist to speed up installation

update composer command

---

src/Controller/UsersController.php
src/Template/Users/index.ctp

Fix the rank in the users list

---

config/Schema/xeta.sql
src/Controller/Admin/CategoriesController.php
src/Model/Entity/BlogCategory.php
src/Model/Table/BlogCategoriesTable.php
src/Template/Admin/Categories/add.ctp
src/Template/Admin/Categories/edit.ctp

Add I18n to the BlogCategories

---

src/Template/Blog/archive.ctp
src/Template/Blog/article.ctp
src/Template/Blog/category.ctp
src/Template/Blog/index.ctp
src/Template/Blog/search.ctp

Use pluralize translate function instead of conditions

---

src/Template/Element/Forum/Thread/posts.ctp

Remove "Quote" button in post when a thread is closed

---

src/Controller/Forum/ThreadsController.php
src/Template/Element/Forum/categories.ctp
src/View/Helper/ForumHelper.php

Fixed bugs in LastPosts Forum

---

src/Controller/Forum/ForumController.php
src/Template/Element/Forum/categories.ctp

Add title in the LastPost

---

src/Controller/Forum/ThreadsController.php
src/Template/Element/Forum/Thread/reply.ctp
src/Template/Forum/Element/Flash/thread_reply.ctp

Ref : https://xeta.io/forum/threads/non-affichage-des-erreurs-de-validations-action-reply.9

Fixed validation error message when replying to a thread

---

src/Controller/Admin/UsersController.php
src/Template/Admin/Users/index.ctp

Ref : https://xeta.io/forum/threads/admin-recherche-user-avec-filtre-by-group.14

Added group option to the user finder in Admin

---

.gitignore
README.md
composer.json
config/bootstrap.php
config/recaptcha.default.php
src/Console/Installer.php
src/Controller/UsersController.php
src/Template/Users/login.ctp
tests/TestCase/Controller/UsersControllerTest.php

Added Google Recaptcha on the Register form

---

.travis.yml
tests/bootstrap.php

Ref : https://github.com/travis-ci/travis-ci/issues/3781

Fix travis

---

src/Template/Element/Forum/Thread/actions.ctp

Remove "Unlock" button for user who are not staff and who are not the owner of the thread

---

config/Schema/xeta.sql
src/Event/Forum/Notifications.php
src/Template/Users/notifications.ctp
tests/Fixture/NotificationsFixture.php
tests/TestCase/Controller/UsersControllerTest.php
tests/TestCase/Event/NotificationsTest.php

Prevent the notifications spam when like/unlike a post.

---

src/Controller/UsersController.php
src/Template/Users/profile.ctp

Latest Blog Articles on user's profile page are not ordered in DESC

---

README.md

Ref : #131 
https://github.com/Xety/Xeta/wiki/How-to-configure-the-server

Add note about session configuration in php.ini

---

config/routes.php
src/Controller/Admin/UsersController.php
src/Controller/Chat/ChatController.php
src/Controller/UsersController.php
src/Model/Table/UsersTable.php
src/Template/Admin/Users/edit.ctp
src/Template/Admin/Users/search.ctp
src/Template/Blog/archive.ctp
src/Template/Blog/article.ctp
src/Template/Blog/category.ctp
src/Template/Blog/index.ctp
src/Template/Blog/search.ctp
src/Template/Cell/Blog/sidebar.ctp
src/Template/Cell/Forum/sidebar.ctp
src/Template/Cell/Forum/suggestion.ctp
src/Template/Element/Forum/Category/threads.ctp
src/Template/Element/Forum/Index/statistics.ctp
src/Template/Element/Forum/Thread/posts.ctp
src/Template/Element/Forum/categories.ctp
src/Template/Element/header.ctp
src/Template/Pages/home.ctp
src/Template/Premium/success.ctp
src/Template/Users/index.ctp
tests/TestCase/Controller/UsersControllerTest.php
tests/TestCase/Model/Table/UsersTableTest.php

Change all User/profile URL to use a slug + ID

---

composer.json
config/routes.php
config/xeta.php
src/Controller/GroupsController.php
src/Template/Admin/Articles/index.ctp
src/Template/Element/Forum/Index/statistics.ctp
src/Template/Groups/view.ctp

View Member by Group and fix the link in the statistics.ctp

---

config/routes.php
src/Controller/BlogController.php
src/Template/Admin/Articles/index.ctp
src/Template/Admin/Attachments/index.ctp
src/Template/Admin/Categories/index.ctp
src/Template/Blog/archive.ctp
src/Template/Blog/article.ctp
src/Template/Blog/category.ctp
src/Template/Blog/index.ctp
src/Template/Blog/search.ctp
src/Template/Cell/Blog/sidebar.ctp
src/Template/Pages/home.ctp
src/Template/Users/profile.ctp
src/View/Cell/BlogCell.php

Fix all Blog : Articles/Categories link by adding slug + ID

---

src/Controller/UsersController.php
src/Template/Email/html/register.ctp

Send a welcome mail on register.

---

config/Schema/xeta.sql
src/Controller/Admin/UsersController.php
src/Controller/AppController.php
src/Controller/UsersController.php
tests/Fixture/UsersFixture.php

Rework the Delete account function.

---

src/Controller/Forum/PostsController.php
src/Controller/Forum/ThreadsController.php
src/Event/Forum/LastPostUpdater.php

Categories LastPost are not updated when a post is deleted.

---

src/Controller/UsersController.php

Fix a bug where the redirect referer is the login page in the login page.

---

src/Controller/UsersController.php

Fixed the error messages in the login page

---

src/Controller/AppController.php
src/Controller/BlogController.php
src/Controller/NotificationsController.php
src/Controller/PagesController.php
src/View/AppView.php
tests/TestCase/Controller/ContactControllerTest.php
tests/TestCase/Controller/UsersControllerTest.php

Replaced the $helpers $components with the initialize method in all controllers.

---

src/Controller/Admin/AdminController.php
src/Controller/Admin/ArticlesController.php
src/Controller/BlogController.php
src/Controller/PagesController.php
src/Event/Statistics.php
src/Shell/Task/ClearCacheTask.php
src/Template/Admin/Admin/home.ctp
src/Template/Pages/home.ctp
webroot/js/lib.min.js
webroot/js/vendor/appear.min.js

+ Reworked the Admin statistics on the home page to use the cached version
Ref #208

Add the statistics on the Home page

---

src/Controller/Admin/ArticlesController.php
src/Controller/Admin/AttachmentsController.php
src/Controller/Admin/CategoriesController.php
src/Controller/Admin/GroupsController.php
src/Controller/Admin/SettingsController.php
src/Controller/Admin/UsersController.php
src/Controller/AppController.php
src/Controller/AttachmentsController.php
src/Controller/BlogController.php
src/Controller/Component/MaintenanceComponent.php
src/Controller/ContactController.php
src/Controller/ConversationsController.php
src/Controller/NotificationsController.php
src/Controller/PollsController.php
src/Controller/TfaController.php
src/Controller/UsersController.php
src/Event/Badges.php
src/Event/Logs.php
src/Event/Users.php
src/I18n/Language.php
src/Template/Cell/Conversations/sidebar.ctp
src/Template/Conversations/create.ctp
src/Template/Conversations/view.ctp
src/Template/Element/Admin/sidebar.ctp
src/Template/Element/Users/sidebar.ctp
src/Template/Element/header.ctp
src/Template/Layout/default.ctp

Updated $event->data to Cake 3.4

---

src/Template/Admin/Articles/index.ctp
src/Template/Admin/Attachments/index.ctp
src/Template/Admin/Categories/index.ctp
src/Template/Admin/Groups/index.ctp
src/Template/Admin/Settings/index.ctp
src/Template/Admin/Users/edit.ctp
src/Template/Admin/Users/search.ctp

Optimize i18Format to use the new TimeHelper
